static const uint8_t girl[]=
"                       .&dkl`,ivne._\n"
"                      sRfkgvc+rsnmGBND.\n"
"                    aHBNLbni+.irumLGNMms\n"
"                    NRIr`'+dLKNMFb`'iNQr\n"
"                   `ANWM7    `+lM0.  `'^Kl\n"
"                   iNWL*_;=e.     Y._,_ ON\n"
"                   aRNm   _.l,    j^ _` Bq,\n"
"                   eNL:,l=N0`.   ls`N0> ibK\n"
"                   XHZu!       _(c      kPBN\n"
"                    'CD   .     `      tK7KX\n"
"                      'f     _&zrc_.  .Y\n"
" ,                      v,   `ta.=\"  ,V\n"
"7q. 6%                   ^l     =   .r\n"
"f'noib. +                `d+   .._a7                     t\n"
"k+RD6 L.dr                h'  `*+iPb                  .f adI`\n"
"dj+Ggr 4NJb            .,dT     `'KJc                 _ir+4b .\n"
"  `cl^ ._ tk.   .,&;:rf\"t&;       'yIKbr;.         dp` luhrZti\n"
"     `~.  ^_T `ysf'      \" n,     7     *lkr,.   i7k._m.JKiV\"\n"
"        J  .H dY   `\"-              ._``    \"VK,4=   . Kdj`\n"
"        K   K B               -s&.            eJ+  .ys7^`\n"
"        T   lLj                               (C' .4\n"
"        P   'y    .,                      .   +j  7\n"
"       ,y   b,     l          .`         ,t   Y`  Y\n"
"       4`    i     J`         g,         ti  .l   k\n"
"       Y     G    p\"  -                -  \"i`J    p\n"
"       L     .~  74. `W`              '`W  9+y    b.\n"
"       N       .Y 6s,     _.      ..      ;T;     gl\n"
"       A       y   *Yf+:'`        `^*:pfjVK+i     tb\n"
"        Y.   j\"     K                  .J`X.f     ly\n"
"         Tj V       T.                 il .Vj    .j'\n"
"          +'        fi                 J`   L.   y\n"
"                    'y        -       .Y     Yz,V\n"
"                    .7        .       'A       +\n"
"                   .V        ,i        Tj\n"
"                  xY         fG         ki\n"
"                 tl                      K.\n"
"                 K                        Jb\n"
"                ,I                        zH\n"
"                T                          I\n"
"                K                           N\n"
"               iU                   .`      P.\n"
"               V       `.   _7_`  _^        Rg\n"
"              .B          `dJNMHb^          dl\n"
"              rG            'YKB`           d'\n"
"              ls             `T;            f\n"
"              'MWMNBKbri++    Y            il\n"
"               VMWNRKtirdJNMWNZ   _.++ttKRNNs\n"
"                VBKkrze+rdRBNMNkr++iittKKBNN\n"
"                `VRttii++rrddNMNBKii++ddZZYe\n"
"                 Yttii+;rrddZBNNNttiirrddZl\n"
"                  Kttii;+rrddNMNKKii++ddZV'\n"
"                  `Vii+;rrddZBNNNttiirrddf\n"
"                   ltii+;rrddNWNKKii++ddZ\n"
"                   'ii++;iddZBNNNttiirrd'\n"
"                    tii+;;rddNMNKKii++dV\n"
"                    'i++r;ddZBNNNttiirrj\n"
"                     ii++irddNMNKKii++dl\n"
"                     i+:irddBNKNNtti+rri\n"
"                     ii+,:rddN NKKb+,;dd\n"
"                    ,i+.;iddMV VMNBb.ird\n"
"                    li,;xdRMB   XMBkrddZ.\n"
"                   .ii+zBRMKX   HSMBbrrd,\n"
"                   ili+inGBKJ   XKbm++ddZ\n"
"                   rii++irdRZ  ,GKtiirrdd.\n"
"                   ltii++rzkd  lKKii++ddZi\n"
"                   tii++rrddZ  BHttiirrdf'\n"
"                   ttii++rxd'  KRbii++dd7\n"
"                   tri:+rrdf   'Nbtii+rdl\n"
"                   'Yi;++rB'    KKii++dd\n"
"                    Bt:+rrf     'Rbii+rd\n"
"                    'ii++H`      Kbi++dl\n"
"                     V+irf       \"KiirP\n"
"                    ,Zli7        `Yi+rd\n"
"                     Z;bK         tk;rl\n"
"                    tii+K         Xli+i\n"
"                   si;+it         AkirY.\n"
"                  etritkl        ;ffi+ds\n"
"                 fltiielf         Kbzrire\n"
"                 HKltfdN'         NBKlfBH\n"
"         b'ger   NMBblB7          VMNKblKl\n"
"                 dBMN9             VKBNM7\n"
"                                      '`\n"
;
